
import java.util.ArrayList;

public class Combobox extends javax.swing.JFrame {

    ArrayList<String> primero = new ArrayList();
    ArrayList<String> segundo = new ArrayList();

    public Combobox() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Instrucciones = new javax.swing.JLabel();
        textfield_modulos = new javax.swing.JTextField();
        boton_añadir = new javax.swing.JButton();
        comboBox_modulos = new javax.swing.JComboBox<>();
        boton_añadirTodo = new javax.swing.JButton();
        boton_borrarTodo = new javax.swing.JButton();
        comboBox_cursos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar elementos combox");
        setName("frame_combox"); // NOI18N
        setResizable(false);

        Instrucciones.setText("Añade el nombre de los módulos de los que estés matriculado:");

        boton_añadir.setText("Añadir");
        boton_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_añadirActionPerformed(evt);
            }
        });

        boton_añadirTodo.setText("Añadir todos");
        boton_añadirTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_añadirTodoActionPerformed(evt);
            }
        });

        boton_borrarTodo.setText("Borrar todos");
        boton_borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrarTodoActionPerformed(evt);
            }
        });

        comboBox_cursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Instrucciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfield_modulos, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBox_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBox_modulos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_añadirTodo)
                            .addComponent(boton_borrarTodo))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Instrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBox_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_modulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox_modulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_añadirTodo)
                    .addComponent(boton_añadir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_borrarTodo)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_añadirActionPerformed
        // TODO add your handling code here:

        if (comboBox_cursos.getItemAt(0).equals("Primero")) {
            primero.add("1º " + textfield_modulos.getText());
        }

        if (comboBox_cursos.getItemAt(1).equals("Segundo")) {
            segundo.add("2º " + textfield_modulos.getText());
        }
    }//GEN-LAST:event_boton_añadirActionPerformed

    private void boton_borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrarTodoActionPerformed
        // TODO add your handling code here:
        comboBox_modulos.removeAllItems();
        primero.clear();
        segundo.clear();
    }//GEN-LAST:event_boton_borrarTodoActionPerformed

    private void boton_añadirTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_añadirTodoActionPerformed
        // TODO add your handling code here:
        if (comboBox_cursos.getSelectedItem().equals("Primero")) {
            mostrarModulos(primero);
        }
        if (comboBox_cursos.getSelectedItem().equals("Segundo")) {
            mostrarModulos(segundo);
        }
    }//GEN-LAST:event_boton_añadirTodoActionPerformed

    private void mostrarModulos(ArrayList<String> curso){
        for (int i = 0; i < curso.size(); i++) {
            comboBox_modulos.addItem(curso.get(i));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Combobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JButton boton_añadir;
    private javax.swing.JButton boton_añadirTodo;
    private javax.swing.JButton boton_borrarTodo;
    private javax.swing.JComboBox<String> comboBox_cursos;
    private javax.swing.JComboBox<String> comboBox_modulos;
    private javax.swing.JTextField textfield_modulos;
    // End of variables declaration//GEN-END:variables
}
